-- address
INSERT INTO address (id, city, street, zip_code, latitude, longitude, info, country_id, region_id, sub_region_id, type)
VALUES (NEXTVAL('address_id_seq'), 'м. Кагарлик', 'вул. Лісова 2', null, '49.875233', '30.837870', null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), (SELECT id from region where name = 'Кагарлицький район'), 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Київська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), 'смт. Червоноармійськ', 'вул. Манзенка 12', null, '50.58001', '28.15266', null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), (SELECT id from region where name = 'Червоноармійський район'), 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G'),
       (NEXTVAL('address_id_seq'), null, null, null, null, null, null, (SELECT id from country where iso_alpha3code = 'UKR'), (SELECT id from region where name = 'Житомирська область'), null, 'G');
