#!/bin/bash

GROUNDS_PATH="$DBDATA_PATH/grounds"

psql --dbname="$PGDATABASE" --echo-errors << EOF
INSERT INTO ground (id, address_id, name, alias, area, kml, description)
VALUES (NEXTVAL('ground_id_seq'), 1, 'ТОВ "Трипільський Мисливець"', 'tov-trypillian-hunter', 49400, lo_import('$GROUNDS_PATH/kyiv/1-tov-tripilskij-mislivec.kml'), 'Полювання в 45км від Києва - це мисливське господарство «Трипільське мисливець».'||E'\n'||'На території в 50 тисяч гектар проводиться колективне та індивідуальне полювання на трофейного кабана і європейську козулю, полювання на польову і водоплавну дичину, на хутрових звірів. Натаска собак на кабана у вольєрі.'||E'\n'||'На території «Трипільського мисливця» розташований мисливський будиночок зі зручностями, кухнею і обіднім залом.'),
       (NEXTVAL('ground_id_seq'), 2, 'ПП "Соколине полісся"', 'sokolyne-polissya', 11800, lo_import('$GROUNDS_PATH/kyiv/2-pp-sokoline-polissya.kml'), ''),
       (NEXTVAL('ground_id_seq'), 3, 'Дочірнє підприємство "Бориспільське районне мисливсько-рибальське господарство Київського об''єднання Київської обласної ради УТМР"', 'boryspilske-rayonne-myslyvsko-rybalske-hospodarstvo', 44518, lo_import('$GROUNDS_PATH/kyiv/3-dp-borispilske-rajonne-mislivsko-ribalske-gospodarstvo.kml'), ''),
       (NEXTVAL('ground_id_seq'), 4, 'ТОВ "Мисливський та спортивний клуб "КАМПА-1"', 'kampa-1', 8123, lo_import('$GROUNDS_PATH/kyiv/4-tov-mislivskij-ta-sportivnij-klub-kampa-1.kml'), ''),
       (NEXTVAL('ground_id_seq'), 5, 'ТОВ "Мисливський та спортивний клуб "КАМПА-2"', 'kampa-2', 22562, lo_import('$GROUNDS_PATH/kyiv/5-tov-mislivskij-ta-sportivnij-klub-kampa-2.kml'), ''),
       (NEXTVAL('ground_id_seq'), 6, 'ТОВ "Сафарі-Авангард"', 'safari-avanhard', 6180.5, lo_import('$GROUNDS_PATH/kyiv/6-tov-safari-avangard.kml'), ''),
       (NEXTVAL('ground_id_seq'), 7, 'ТОВ "Гран - Мисливство"', 'hran-myslyvstvo', 26530.9, lo_import('$GROUNDS_PATH/kyiv/7-tov-gran-mislivstvo.kml'), ''),
       (NEXTVAL('ground_id_seq'), 8, 'ТОВ "Мисливсько-рибальський клуб "Відродження"', 'vidrodzhennya', 3200, lo_import('$GROUNDS_PATH/kyiv/8-tov-mislivsko-ribalskij-klub-vidrodzhennya.kml'), ''),
       (NEXTVAL('ground_id_seq'), 9, 'ТОВ "Ржищівське мисливське господарство"', 'rzhyshchivske-myslyvske-hospodarstvo', 44800, lo_import('$GROUNDS_PATH/kyiv/9-tov-rzhishivske-mislivske-gospodarstvo.kml'), ''),
       (NEXTVAL('ground_id_seq'), 10, 'ТОВ "Поле-Вовк"', 'pole-vovk', 19348, lo_import('$GROUNDS_PATH/kyiv/10-tov-pole-vovk.kml'), ''),
       (NEXTVAL('ground_id_seq'), 11, 'ТОВ "Оксамит-Сервіс"', 'oksamyt-servis', 20000, lo_import('$GROUNDS_PATH/kyiv/11-tov-oksamit-servis.kml'), ''),
       (NEXTVAL('ground_id_seq'), 12, 'ТОВ "Українські лови"', 'ukrayinski-lovy', 20750, lo_import('$GROUNDS_PATH/kyiv/12-tov-ukrayinski-lovi.kml'), ''),
       (NEXTVAL('ground_id_seq'), 13, 'ТОВ "Ю 2"', 'yu-2', 9815.6, lo_import('$GROUNDS_PATH/kyiv/13-tov-yu-2.kml'), ''),
       (NEXTVAL('ground_id_seq'), 14, 'ТОВ "Мисливсько-рибальський клуб "Дружба"', 'druzhba', 19796, lo_import('$GROUNDS_PATH/kyiv/14-tov-mislivsko-ribalskij-klub-druzhba.kml'), ''),
       (NEXTVAL('ground_id_seq'), 15, 'ТОВ "Мисливсько-рибальський клуб "Ласка"', 'laska', 12099, lo_import('$GROUNDS_PATH/kyiv/15-tov-mislivsko-ribalskij-klub-laska.kml'), ''),
       (NEXTVAL('ground_id_seq'), 16, 'ТОВ "Мисливсько-рибальський клуб "Ярик"', 'yaryk', 30800, lo_import('$GROUNDS_PATH/kyiv/16-tov-mislivsko-ribalskij-klub-yarik.kml'), ''),
       (NEXTVAL('ground_id_seq'), 17, 'ТОВ "Мисливське господарство "Ошитки"', 'oshytky', 11300, lo_import('$GROUNDS_PATH/kyiv/17-tov-mislivske-gospodarstvo-oshitki.kml'), ''),
       (NEXTVAL('ground_id_seq'), 18, 'ТОВ "Мисливське господарство "Київське"', 'kyyivske', 17966, lo_import('$GROUNDS_PATH/kyiv/18-tov-mislivske-gospodarstvo-kiyivske.kml'), ''),
       (NEXTVAL('ground_id_seq'), 19, 'ТОВ "Мисливське господарство "БРЕТОН"', 'breton', 10821, lo_import('$GROUNDS_PATH/kyiv/19-tov-mislivske-gospodarstvo-breton.kml'), ''),
       (NEXTVAL('ground_id_seq'), 20, 'ТОВ "Мисливський клуб "СКС"', 'myslyvskyy-klub-sks', 18359.1, lo_import('$GROUNDS_PATH/kyiv/20-tov-mislivskij-klub-sks.kml'), ''),
       (NEXTVAL('ground_id_seq'), 21, 'ГО "Мисливсько-рибальський клуб "Кречет"', 'krechet', 24100, lo_import('$GROUNDS_PATH/kyiv/21-go-mislivsko-ribalskij-klub-krechet.kml'), ''),
       (NEXTVAL('ground_id_seq'), 22, 'ГО "Об''єднання по збереженню та відтворенню природи "Обрій"', 'obriy', 10400, lo_import('$GROUNDS_PATH/kyiv/22-go-obyednannya-po-zberezhennyu-ta-vidtvorennyu-prirodi-obrij.kml'), ''),
       (NEXTVAL('ground_id_seq'), 23, 'ГО "Мисливсько-рибальський клуб "Васильківщина"', 'vasylkivshchyna', 39800, lo_import('$GROUNDS_PATH/kyiv/23-go-mislivsko-ribalskij-klub-vasilkivshina.kml'), ''),
       (NEXTVAL('ground_id_seq'), 24, 'Поліська районна громадська організація мисливців і рибалок "Поліський край"', 'poliskyy-kray', 13100, lo_import('$GROUNDS_PATH/kyiv/24-poliska-rajonna-gromadska-organizaciya-mislivciv-i-ribalok-poliskij-kraj.kml'), ''),
       (NEXTVAL('ground_id_seq'), 25, 'Таращанське районне громадське об''єднання "Мисливці та рибалки"', 'tarashchanske-rayonne-hromadske-obyednannya-myslyvtsi-ta-rybalky', 4103, lo_import('$GROUNDS_PATH/kyiv/25-tarashanske-rajonne-gromadske-obyednannya-mislivci-ta-ribalki.kml'), ''),
       (NEXTVAL('ground_id_seq'), 26, 'ТОВ "Мисливці Полісся"', 'tov-myslyvtsi-polissya', 6763.6, lo_import('$GROUNDS_PATH/zhytomyr/26-tov-mislivci-polissya.kml'), 'Отримайте унікальний досвід полювання в екологічному господарстві, пересування по якому здійснюється виключно на гужовому транспорті!'||E'\n'||'Мисливське господарство «Мисливці Полісся» розташоване в 200 км від Києва, займає площу в 6700га лісових, польових і водно-болотних угідь.'||E'\n'||'Проводиться індивідуальне (в тому числі і з вишки) і колективне полювання на трофейного лося, кабана, косулю, хутрових звірів та пернату дичину, рибалка з вимостків - ставок 16га (сом, судак, щука, окунь, короп, лин, червоний карась).'),
       (NEXTVAL('ground_id_seq'), 27, 'Новоград-Волиський міськрайонний ТМР "Сокіл"', 'sokil', 5532.74, lo_import('$GROUNDS_PATH/zhytomyr/27-novograd-voliskij-miskrajonnij-tmr-sokil.kml'), ''),
       (NEXTVAL('ground_id_seq'), 28, 'ГО "Мисливсько-рибальський клуб "Діана"', 'diana', 5114, lo_import('$GROUNDS_PATH/zhytomyr/28-go-mislivsko-ribalskij-klub-diana.kml'), ''),
       (NEXTVAL('ground_id_seq'), 29, 'ГО "МРК "Компас"', 'kompas', 4479.6, lo_import('$GROUNDS_PATH/zhytomyr/29-go-mrk-kompas.kml'), ''),
       (NEXTVAL('ground_id_seq'), 30, 'ГО "Мисливський клуб "Блазер"', 'blazer', 3267, lo_import('$GROUNDS_PATH/zhytomyr/30-go-mislivskij-klub-blazer.kml'), ''),
       (NEXTVAL('ground_id_seq'), 31, 'ГО "Мисливсько-рибальський клуб "Рись-Верби"', 'rys-verby', 3011.1, lo_import('$GROUNDS_PATH/zhytomyr/31-go-mislivsko-ribalskij-klub-ris-verbi.kml'), ''),
       (NEXTVAL('ground_id_seq'), 32, 'ГО МРК "Артеміда"', 'artemida', null, lo_import('$GROUNDS_PATH/zhytomyr/32-go-mrk-artemida.kml'), ''),
       (NEXTVAL('ground_id_seq'), 33, 'ТОВ "Житниця"', 'zhytnytcya', 3165.2, lo_import('$GROUNDS_PATH/zhytomyr/33-tov-zhitnicya.kml'), ''),
       (NEXTVAL('ground_id_seq'), 34, 'ТОВ "Мисливський клуб "Хантер"', 'hanter', 5143.7, lo_import('$GROUNDS_PATH/zhytomyr/34-tov-mislivskij-klub-hanter.kml'), ''),
       (NEXTVAL('ground_id_seq'), 35, 'ТОВ МРК "Війсьових ветеранів"', 'viyskovykh-veteraniv', 3581.8, lo_import('$GROUNDS_PATH/zhytomyr/35-tov-mrk-vijsovih-veteraniv.kml'), ''),
       (NEXTVAL('ground_id_seq'), 36, 'ТОВ "Квінта плюс компані"', 'kvinta-plyus-kompani', 3668.5, lo_import('$GROUNDS_PATH/zhytomyr/36-tov-kvinta-plyus-kompani.kml'), ''),
       (NEXTVAL('ground_id_seq'), 37, 'Житомирський обласний мисливсько-рибальський клуб "Фауна"', 'fauna', 3059.3, lo_import('$GROUNDS_PATH/zhytomyr/37-zhitomirskij-oblasnij-mislivsko-ribalskij-klub-fauna.kml'), ''),
       (NEXTVAL('ground_id_seq'), 38, 'Житомирська обласна громадська організація "Захист"', 'zahyst', 3152.8, lo_import('$GROUNDS_PATH/zhytomyr/38-zhitomirska-oblasna-gromadska-organizaciya-zahist.kml'), ''),
       (NEXTVAL('ground_id_seq'), 39, 'ДП "Овруцьке спеціалізоване лісове господарство"', 'ovrutske', 5125, lo_import('$GROUNDS_PATH/zhytomyr/39-dp-ovrucke-specializovane-lisove-gospodarstvo.kml'), ''),
       (NEXTVAL('ground_id_seq'), 40, 'ДП "Ємельчинське лісове господарство"', 'yemelchynske', 36922, lo_import('$GROUNDS_PATH/zhytomyr/40-dp-yemelchinske-lisove-gospodarstvo.kml'), ''),
       (NEXTVAL('ground_id_seq'), 41, 'ДП "Житомирський військовий лісгосп"', 'zhytomyrskyy-viyskovyy-lishosp', 1607.8, lo_import('$GROUNDS_PATH/zhytomyr/41-dp-zhitomirskij-vijskovij-lisgosp.kml'), ''),
       (NEXTVAL('ground_id_seq'), 42, 'ДП "Овруцьке лісове господарство"', 'ovrutske-lisove-hospodarstvo', 5668, lo_import('$GROUNDS_PATH/zhytomyr/42-dp-ovrucke-lisove-gospodarstvo.kml'), ''),
       (NEXTVAL('ground_id_seq'), 43, 'ГО "Радомишльські мисливці"', 'radomishlski-mislivci', 4906.7, lo_import('$GROUNDS_PATH/zhytomyr/43-go-radomishlski-mislivci.kml'), ''),
       (NEXTVAL('ground_id_seq'), 44, 'ДП "Бердичівське лісове господарство"', 'berdichivske-lisove-gospodarstvo', 3924, lo_import('$GROUNDS_PATH/zhytomyr/44-dp-berdichivske-lisove-gospodarstvo.kml'), ''),
       (NEXTVAL('ground_id_seq'), 45, 'Малинська районна громадська організація "Товариство мисливців та рибалок"', 'malinska-rajonna-gromadska-organizaciya-tovaristvo-mislivciv-ta-ribalok', 3661.21, lo_import('$GROUNDS_PATH/zhytomyr/45-malinska-rajonna-gromadska-organizaciya-tovaristvo-mislivciv-ta-ribalok.kml'), '');
EOF
