application:
  security:
    google-maps-api-key: ${GOOGLE_MAPS_API_KEY}

server:
  port: ${PORT}

spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true # Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
